### ISSUE TITLE
depends on go 1.5+?

### ISSUE THREAD

**Issue by newhook** [tylerb/graceful#68] opened 2016-05-26 14:25 UTC
I'm using go 1.4 and graceful no longer works.

```
# golang.org/x/net/http2
/Users/matthew/go/src/golang.org/x/net/http2/transport.go:213: req.Cancel undefined (type *http.Request has no field or method Cancel)
/Users/matthew/go/src/golang.org/x/net/http2/transport.go:217: req.Cancel undefined (type *http.Request has no field or method Cancel)
/Users/matthew/go/src/golang.org/x/net/http2/transport.go:776: req.Cancel undefined (type *http.Request has no field or method Cancel)
```

**Comment by tylerb** [comment] 2016-05-26 15:00
Hey @newhook!

I'm not sure what's going on with your build, but I think it may be unrelated to graceful. If you check out https://travis-ci.org/tylerb/graceful you'll see that it successfully built and ran tests on targets from 1.3.3 to 1.6.2, though tip seems to be having some issues.

**Comment by newhook** [comment] 2016-05-26 15:08
I'm pretty sure its because go get on graceful fetches golang.org/x/net for netutil (and then transitively x/net/http2 due to the listen_test.go in netutil) and x/net/http2 no longer supports go 1.4. 

graceful itself doesn't use that stuff, but the transitive get causes issues.

**Comment by tylerb** [comment] 2016-05-26 16:47
Well, rats. It is interesting that it seems to work fine on travis, which is doing a `go get` as well. Not sure what's up with that.

I'm not sure what the correct approach here is. Vendoring graceful and an older version of http2/netutil to make it work on 1.4 would be about the only thing I can think of to fix it for you. Any thoughts on this?

**Comment by newhook** [comment] 2016-05-26 16:58
I didn't look at the impl but avoiding the use of netutil would the simplest solution :)

**Comment by tylerb** [comment] 2016-05-26 16:59
I'll take a look at it and see if that's doable. Thanks Matthew!

**Comment by tylerb** [comment] 2016-06-03 16:36
@F21 any thoughts here?

**Comment by F21** [comment] 2016-06-04 02:36
I had a quick look at the files in `netutil` and they don't contain any references to `x/net/http2`. 

@newhook Can you try again to see if it builds? If it still doesn't build, do you mind posting a repository to reproduce?

Thanks :smile:

**Comment by newhook** [comment] 2016-06-04 02:47
It was the tests.

**Comment by newhook** [comment] 2016-06-04 02:58
I just tried the latest and I'm not getting issues... not sure what changed. I'll try it in our repo again on Monday and make sure that has no issues.

**Comment by F21** [comment] 2016-06-04 04:08
@newhook:

I just created a repo running a graceful http server in a Go 1.4.3 docker container and it appears to work correctly.

See: https://github.com/F21/graceful-go1.4

You might have other depenencies in your project that is pulling in `x/net/http2`.

**Comment by tylerb** [comment] 2016-06-06 16:26
@newhook any update on this? I'd like to close it if possible.

**Comment by F21** [comment] 2016-06-13 05:47
@newhook were you able to resolve this?

**Comment by tylerb** [comment] 2016-06-20 17:10
Closing this issue as no response in two weeks

**Closed by tylerb** 2016-06-20 17:10 UTC

**Comment by newhook** [comment] 2016-06-20 22:09
Sorry, I didn't get a chance to retest. We're moving off go 1.4 completely soon anyway :)
